inicio
    variavel real nota1 , nota2 , nota3 , nota4,MEDIA
    escrever "ENTRE COM A NOTA 1"
    ler nota1
    escrever "ENTRE COM A NOTA 2"
    ler nota2
    escrever "ENTRE COM A NOTA 3"
    ler nota3
    escrever "ENTRE COM A NOTA 4"
    ler nota4
    
    media <-(nota1+nota2+nota3+nota4)/4
    escrever media
    escrever "...."
    se media >= 7.0 entao
        escrever "APROVADO"
    senao
        escrever "REPROVADO"
    fimse
fim

